/*
============== Java Programming II ==============
Part 8
Section 3 - Similarity of objects
Ex 13 - Vehicle Registry 


Implement a program for registering vehicle owners and license plates using a HashMap.
=================================================
*/

import java.util.Objects;

public class LicensePlate {
    // don't modify existing parts of this class

    // these instance variables have been defined as final, meaning 
    // that once set, their value can't be changed
    private final String liNumber;
    private final String country;

    public LicensePlate(String country, String liNumber) {
        this.liNumber = liNumber;
        this.country = country;
    }

    @Override
    public String toString() {
        return country + " " + liNumber;
    }

    /* The hashCode method below is generated by the IDE 
    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.liNumber);
        hash = 79 * hash + Objects.hashCode(this.country);
        return hash;
    }*/
    
    // Here is my version
    @Override
    public int hashCode() {
        return this.liNumber.hashCode() + this.country.hashCode();
    }
    

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LicensePlate other = (LicensePlate) obj;
        return (this.liNumber.equals(other.liNumber) && this.country.equals(other.country));
    }

}
